#!/usr/bin/env bash

set -e -o pipefail

# Compile output from Resummino into a Twiki friendly format and produce a plot

# TODO: Make plot with cross sections
# TODO: Think about how to combine C1+N2 and C1-N2, but also all hino processes
# TODO: Currently one log file per positional parameter is generated, these
#       should be combined
# TODO: Give the user some control over verbosity of this script

# Use echo to output to stderr
errcho(){
    >&2 echo ${@}
}

# Output to Twiki log file
twikilog(){
    echo "${@} " >> "${twikilog}"
}

# Get input directory from positional argument
get_inputdir(){
    # Check that input directory is defined
    if [ ! -d "${1}" ]; then
        echo -n "Need path to directory with Resummino logs "
        echo "as first positional argument."
        echo "Exit."
        exit 1
    fi

    inputdir="${1}"

    # Remove all trailing slashes from inputdir
    while [[ "${inputdir: -1}" == / ]]; do
        inputdir="${inputdir%/}"
    done
}

# Make sure that you pick up the right cross section
check_xs_format(){
    # Compare format up to "(" character with expected format in the log files
    local xs_log="${1%(*}"
    local exp_log="${2}"
    if [[ ! "${xs_log}" == "${exp_log} = " ]]; then
        echo "Could not determine ${exp_log} cross section."
        echo "Exit."
        exit 2
    fi
}

# Extract cross section from log file
get_xs(){
    echo $(sed 's/^.*(\([^ ]*\).*/\1/' <<< "${1}")
}

# Extract uncertainty on cross section from log file
get_err(){
    echo $(sed 's/^.*+- \([^)]*\).*/\1/' <<< "${1}")
}

# Return "float" rounded to 4 significant digits
round_values_4(){
    local value="${1}"
    awk '{printf("%.4g\n", 1000*$0)}' <<< "${value}"
}

# Return "float" rounded to 5 significant digits
round_values_5(){
    local value="${1}"
    awk '{printf("%.5g\n", 1000*$0)}' <<< "${value}"
}

# Get human readable version of the model
get_hr_slha(){
    if [ "${slha}" == wino ]; then
        echo Wino
    elif [ "${slha}" == hino ]; then
        echo Higgsino
    else
        echo "${slha}"
    fi
}

# Get human readable name of the particle, i.e. translate PDGID to particle name
get_hr_pname(){
    p="${1}"
    if [ "${p}" -eq 1000022 ]; then # N1
        echo "&#967;&#771;<sup>0</sup><sub>1</sub>"
    elif [ "${p}" -eq 1000023 ]; then # N2
        echo "&#967;&#771;<sup>0</sup><sub>2</sub>"
    elif [ "${p}" -eq 1000024 ]; then # C1
        echo "&#967;&#771;<sup>+</sup><sub>1</sub>"
    elif [ "${p}" -eq -1000024 ]; then # C1
        echo "&#967;&#771;<sup>-</sup><sub>1</sub>"
    else
        echo "${p}"
    fi
}

# Add table properties to Twiki log file
add_table_props(){
    # Table properties
    twikilog -n '%TABLE{ tableborder="0" cellpadding="4" cellspacing="3"'
    twikilog -n 'cellborder="1" headerrows="1" columnwidths="80, 125, 125"'
    twikilog -n 'headeralign="center" dataalign="right" headercolor="#FFFFFF"'
    twikilog -n 'headerbg="#437B58" databg="#A1C2B1, #CFDFD5"'
    twikilog 'datacolor="#000000"}%'
    twikilog
}

# Add table header row to Twiki log file
add_table_header(){
    # Table header row
    twikilog -n " | *m<sub>&#967;&#771;</sub> [GeV]* | *&sigma; [fb]*"
    twikilog " | *uncertainty [fb]* |"
}

# Add an entry in the table in the Twiki log file
table_entry(){
    twikilog " | ${1} | ${2} | ${3} |"
}

# Create one log file per positional argument
run(){

    get_inputdir "${1}"

    # Retrieve information from directory name
    local dir="${inputdir##*/}"
    local slha="${dir%%_*}"
    local com="${dir#*_}"
    com="${com%TeV*}"
    local p1="${dir#*_}"
    p1="${p1#*_}"
    local p2="${p1#*_}"
    p1="${p1%_*}"
    p1="${p1/m/-}"
    p2="${p2/m/-}"
    local cluster="${inputdir%/*}"
    cluster="${cluster##*/}"
    local twikilog="${cluster}_${dir}.log"

    # Remove Twiki log file
    rm -f "${twikilog}"

    # Make variables human readable for the Twiki page
    local slha_hr=$(get_hr_slha)
    local p1_hr=$(get_hr_pname "${p1}")
    local p2_hr=$(get_hr_pname "${p2}")

    # Collect various variables in arrays to access them later again for the
    # combination of the log files
    twikilogs+=("${twikilog}")
    p1_hrs+=("${p1_hr}")
    p2_hrs+=("${p2_hr}")
    slha_hrs+=("${slha_hr}")
    coms+=("${com}")

    # Title for Twiki page
    twikilog -n "---+++ NLO+NNLL ${slha_hr} cross sections for"
    twikilog "${p1_hr}${p2_hr} production at sqrt(s) = ${com} !TeV"
    twikilog

    add_table_props
    add_table_header

    for log in "${inputdir}"/*; do

        echo "Check log file ${log}."

        local mass="${log##*_}"
        mass="${mass%.log}"

        # Get cross sections (LO, NLO and NLO+NNLL)
        # Since sed exits, there is no-one reading the piped output of tac anymore
        # and tac will return exit code 141 (SIGPIPE); we don't want that to stop
        # the program, though, so we turn off pipefail for a moment
        set +o pipefail
        local lo_log="$(tac "${log}" | sed -n '5{p;q}')"
        local nlo_log="$(tac "${log}" | sed -n '4{p;q}')"
        local nlonnll_log="$(tac "${log}" | sed -n '3{p;q}')"
        set -o pipefail

        # Check if these are indeed cross sections by comparing to the expected
        # format from Resummino
        check_xs_format "${lo_log}" "LO"
        check_xs_format "${nlo_log}" "NLO"
        check_xs_format "${nlonnll_log}" "NLO+NLL"

        # Extract cross sections and uncertainties from log entry
        local lo=$(get_xs "${lo_log}")
        local lo_err=$(get_err "${lo_log}")
        local nlo=$(get_xs "${nlo_log}")
        local nlo_err=$(get_err "${nlo_log}")
        local nlonnll=$(get_xs "${nlonnll_log}")
        local nlonnll_err=$(get_err "${nlonnll_log}")

        # Round values
        lo=$(round_values_5 "${lo}")
        lo_err=$(round_values_4 "${lo_err}")
        nlo=$(round_values_5 "${nlo}")
        nlo_err=$(round_values_4 "${nlo_err}")
        nlonnll=$(round_values_5 "${nlonnll}")
        nlonnll_err=$(round_values_4 "${nlonnll_err}")

        # Output results
        echo "LO:       ${lo} +/- ${lo_err}"
        echo "NLO:      ${nlo} +/- ${nlo_err}"
        echo "NLO+NNLL: ${nlonnll} +/- ${nlonnll_err}"
        table_entry "${mass}" "${nlonnll}" "${nlonnll_err}"

    done
}

# Check that all elements are the same
check_elements_same(){
    local dscrptn="${1}"
    shift
    local element
    for element; do
        # Compare old_element with element; if old_element is not set,
        # substitute with element and the comparison is trivially true
        if [ "${old_element-${element}}" != "${element}" ]; then
            echo -n "You try to combine different ${dscrptn}, which does not "
            echo -n "make much sense. Offending values are: "
            echo "${old_element} / ${element}"
            echo "Exit."
            exit 3
        fi
        local old_element="${element}"
    done
}

# Combine all separate log files
combine(){

    # Combined Twiki log
    twikilog=resummino_combined.log

    # Remove combined Twiki log file
    rm -f "${twikilog}"

    # Check that all elements in these arrays are the same, it does not make
    # much sense to combine cross sections for e.g. sqrt(s) of 13 and 14 TeV or
    # for winos and higgsinos
    check_elements_same "center of masses" "${coms[@]}"
    check_elements_same "particle types" "${slha_hrs[@]}"

    # Title for Twiki page, loop over all particle combination
    twikilog -n "---+++ NLO+NNLL ${slha_hrs[0]} cross sections for combined"
    for (( i=0; i<${#p1_hrs[*]}; i++ )); do
        twikilog -n "${and}${p1_hrs[$i]}${p2_hrs[$i]}"
        local and="and "
    done
    twikilog "production at sqrt(s) = ${coms[0]} !TeV"
    twikilog

    add_table_props
    add_table_header

    for log in "${twikilogs[@]}"; do
        twikilog COMBINE
        twikilog "${log}"
    done
}

# Run script for every positional argument
for logs; do
    run "${logs}"
done

# Combine all log files, if there is more than one
if [ $# -gt 1 ]; then
    combine
fi
