#!/usr/bin/env bash

# Submit all relevant cross sections including systematic variations
# This is a total of 574488 jobs!

coms=(13 14 27)
slhas=(hino.in wino.in)

# This exceeds the maximum number of jobs HTCondor is willing to run at once
#for com in "${coms[@]}"; do
#    for slha in "${slhas[@]}"; do
#        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 1000024"  -m "$(echo {50..2000..25})" -u "0.5 1.0 2.0" -x all
#        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 -1000024" -m "$(echo {50..2000..25})" -u "0.5 1.0 2.0" -x all
#        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000024 -1000024" -m "$(echo {50..2000..25})" -u "0.5 1.0 2.0" -x all
#        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000022 1000023"  -m "$(echo {50..2000..25})" -u "0.5 1.0 2.0" -x all
#    done
#done

# Only submit one line at a time
for com in "${coms[@]}"; do
    for slha in "${slhas[@]}"; do
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 1000024"  -m "$(echo {50..2000..25})" -u 0.5 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 -1000024" -m "$(echo {50..2000..25})" -u 0.5 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000024 -1000024" -m "$(echo {50..2000..25})" -u 0.5 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000022 1000023"  -m "$(echo {50..2000..25})" -u 0.5 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 1000024"  -m "$(echo {50..2000..25})" -u 1.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 -1000024" -m "$(echo {50..2000..25})" -u 1.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000024 -1000024" -m "$(echo {50..2000..25})" -u 1.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000022 1000023"  -m "$(echo {50..2000..25})" -u 1.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 1000024"  -m "$(echo {50..2000..25})" -u 2.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000023 -1000024" -m "$(echo {50..2000..25})" -u 2.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000024 -1000024" -m "$(echo {50..2000..25})" -u 2.0 -x all
        ./condor_resummino_submit -s "${slha}" -e "${com}" -p "1000022 1000023"  -m "$(echo {50..2000..25})" -u 2.0 -x all
    done
done
